### ISSUE TITLE
FIX: build_constCoeff.m

### ISSUE THREAD

**Issue by emeltzer** [msperlin/MS_Regress-Matlab#1]
Matlab 2016b no longer supports calling nargin from scripts. Calling function MS_Regress_Fit.m has already been modified to create default advOpt structure, but probably forgot to remove nargin from the script.

`>> Example_MS_Regress_Fit
Error using nargin
You can only call nargin/nargout from within a MATLAB function.

Error in build_constCoeff (line 4)
if nargin()==4||(isfield(advOpt,'constCoeff')==0) % if number of arg < 4, build constraint structure

Error in MS_Regress_Fit (line 216)
build_constCoeff();

Error in Example_MS_Regress_Fit (line 18)
[Spec_Out]=MS_Regress_Fit(dep,indep,k,S,advOpt); % Estimating the model
 `

FIX: build_constCoeff.m
 `
% building constCoeff

% remove unnecessary nargin check
%if nargin()==4||(isfield(advOpt,'constCoeff')==0) % if number of arg < 4, build constraint structure
if isfield(advOpt,'constCoeff')==0 % if advOpt.constCoeff does not exist, build constraint structure
                                                  % and fill it with 'e'
 `

**Comment by msperlin** [comment]
Thanks emeltzer. I just fixed it.
